apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutate-me-webhook
webhooks:
  - name: mutate-me.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        mutate-me-webhook-enabled: "true"
    clientConfig:
      service:
        name: mutate-me
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYRENDQWtTZ0F3SUJBZ0lVYlc2QVEzWVl4OVpYNnlZbjdranJ3STIzUVpBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JqRUxNQWtHQTFVRUJoTUNTVTR4RERBS0JnTlZCQWdUQTBkTFJURU9NQXdHQTFVRUJ4TUZUbTlwWkdFeApEREFLQmdOVkJBb1RBMGRMUlRFTE1Ba0dBMVVFQ3hNQ1EwRXdIaGNOTWpNd01qRTBNRFl5TWpBd1doY05Namd3Ck1qRXpNRFl5TWpBd1dqQkdNUXN3Q1FZRFZRUUdFd0pKVGpFTU1Bb0dBMVVFQ0JNRFIwdEZNUTR3REFZRFZRUUgKRXdWT2IybGtZVEVNTUFvR0ExVUVDaE1EUjB0Rk1Rc3dDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTFFT3dlejhIWXJBK2ZZKzdNRlJsTU1HaEMwWmhLTWxSbUFpdWgvCmZwMWp0VDQvZTZNdTRQdU5EaXhldnNJZHBPVTFtSUMzMmw3aDMrZ3ZsdCtyTVBjTjV2aGNNTXd2SG5vZXBDM2YKb0o4V0tkSysyZVliSXZNTXhDVEhtZGlwOE1LTFNUQ0hBdmptUGcxb2IzSFFQM0pMMW10bWlMaGtsaTRPbnlKdQpxK0lsUEwyZWdiakl6dVZONnJQQkI1MlJVN0toMHRpd0tzUk91UzZSMW5lSGErVGZjUG5ld3poUSs4NjA1Y3l3CnF3c2JGOC9MVVl4QVFRV1VzSzBDSk5PYVBBQUgrQ1dJSHZ6RzJaMVZrditpbWFmSjByelZsYkNXUmlJbk16blYKV3pMaXZFUDVEeVpVLytseDk5MTJHMFhGcEtTNWp0QWY3dlVudUlEYk5HMndueUVDQXdFQUFhTkNNRUF3RGdZRApWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkRTc3JWdCtXMWFhCkhQaWUwajg2RnRBL1V5aWZNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJjQVBjN29GZ2UxOXd5anF6SWtFSmEKVWNGMHo3VmZ0T2hVMXIveHFFRUZVS1orKzFJeEwzYzQvZ2ZEODdkQ0NzREhOclBVcDM0T2VzdGhxZFVJZFpUTgpMWTVWcEQ3cE0zanV2YVQ1U2NYYUtoMTYxelJERDhqUHhDa0pSZmIwRjh4NWJFV1hjQWhaWlpTbmxnSmtWMzVYCmtGL2phYWFuaEZtbHdYWG9ITityK2JJUlZEbndXTkxFSWVCRmRpQjEvS3hvcW1XZ1RFQXJXWGcxYTZ3VEVzZG8KUEJMUFF3VVBKek4xczI0SVdhSVBWWXIvR0ltZGJrejlyMDczYkpoS21MN3BaZjhUSEkwSVdTRVFTbDl2dE1QZApVSG41NnFJeVNkSVh6Ty8zUXVKelpJalMwWTV1S1VZVDZSdmJNWVhzTXcxOE5Yd3VxcTBOd0Y0VCttdmI1eEdTCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]